### ISSUE TITLE
Margo bulk pool segfaulting at finalize time

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-margo#52]
In GitLab by @mdorier on Oct 1, 2019, 05:38

I'm using Bake's pipelining mode (calling `bake_provider_set_config` to set "pipeline_enabled" to "1"). When the provider finalizes, I'm getting a segfault with the following stack trace:

```
#0  0x00007fb8e1444b12 in margo_bulk_pool_destroy (pool=0x4) at src/margo-bulk-pool.c:127
#1  0x00007fb8e1444f2d in margo_bulk_poolset_destroy (poolset=0x561853aef040) at src/margo-bulk-pool.c:290
#2  0x00007fb8e14e3017 in bake_server_finalize_cb (data=data@entry=0x5618515896b0) at ../src/bake-server.c:1840
#3  0x00007fb8e14e3067 in bake_provider_destroy (provider=0x5618515896b0) at ../src/bake-server.c:376
```

**Comment by carns** [comment]
In GitLab by @carns on Apr 8, 2020, 17:18

Does this still happen?  I lost track of this issue somehow :(

It does not trigger in the bake benchmarks, but could very well be happening in other circumstances.

**Comment by carns** [comment]
In GitLab by @mdorier on Apr 8, 2020, 17:27

I'm not sure, I don't recall having found the issue...

**Comment by carns** [comment]
In GitLab by @carns on Apr 9, 2020, 09:52

I think it might have been fixed.  Let's just open a new ticket if it happens again.

**Comment by carns** [comment]
In GitLab by @carns on Apr 9, 2020, 09:52

closed
